### ISSUE TITLE
Check missing config.json

### ISSUE THREAD

**Issue by Imperator26** [leon-ai/leon#114]
### Expected Behavior
It would be ideal to have some kind of warning when starting leon that X package has no `config.json` file.

### Actual Behavior
The package silently doesn't work.

### Proposal
If possible it would be great to add some sort of check when initializing the packages. It would be even better if the check could go look inside the file and check that all modules are set.

**Comment by tangyongfeng** [comment]
➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
Traceback (most recent call last):
  File "bridges/python/main.py", line 20, in <module>
    main()
  File "bridges/python/main.py", line 17, in main
    return getattr(m, queryobj['module'])(queryobj['query'], queryobj['entities'])
  File "./packages/leon/randomnumber.py", line 10, in randomnumber
    return utils.output('end', 'success', randint(0, 100))
  File "/home/***/***/leon/bridges/python/utils.py", line 71, in output
    'options': config('options')
  File "/home/***/***/leon/bridges/python/utils.py", line 92, in config
    file = open(dirname + '/../../packages/' + queryobj['package'] + '/config/config.json', 'r', encoding = 'utf8')
FileNotFoundError: [Errno 2] No such file or directory: '/home/***/***/leon/bridges/python/../../packages/leon/config/config.json'

**Comment by Imperator26** [comment]
This check is not performed when `npm start` is run

**Comment by tangyongfeng** [comment]
ok, thank you!
