### ISSUE TITLE
Mic for hotword crashes and keep blinking unexpectedly most of the time

### ISSUE THREAD

**Issue by soomro30** [leon-ai/leon#134]
Hello. I am using the hotword wakeup for leon. Sometimes the hotword works very fine and suddenly sometimes it hangs with the mic icon blinking and following error message on the console.

main.js:569 Uncaught DOMException: Failed to execute 'start' on 'MediaRecorder': The MediaRecorder's state is 'recording'.
    at Recorder.start (http://localhost:1337/js/main.js:569:21)
    at r.<anonymous> (http://localhost:1337/js/main.js:447:19)
    at r.emit (http://localhost:1337/vendor/socket.io/2.0.3/socket.io.js:1:12375)
    at r.onevent (http://localhost:1337/vendor/socket.io/2.0.3/socket.io.js:2:26816)
    at r.onpacket (http://localhost:1337/vendor/socket.io/2.0.3/socket.io.js:2:26438)
    at r.<anonymous> (http://localhost:1337/vendor/socket.io/2.0.3/socket.io.js:2:28556)
    at r.emit (http://localhost:1337/vendor/socket.io/2.0.3/socket.io.js:1:12375)
    at r.ondecoded (http://localhost:1337/vendor/socket.io/2.0.3/socket.io.js:1:18962)
    at s.<anonymous> (http://localhost:1337/vendor/socket.io/2.0.3/socket.io.js:2:28556)
    at s.r.emit (http://localhost:1337/vendor/socket.io/2.0.3/socket.io.js:1:12375)

**Comment by louistiti** [comment]
Hello @soomro30,

Thanks for reporting. Let me take a look at that once I'm back on Leon.

**Comment by Divlo** [comment]
Thanks for your report!
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
