### ISSUE TITLE
Error with TTS & STT APIs from IBM | Watson when talking to leon

### ISSUE THREAD

**Issue by die3oute** [leon-ai/leon#174]
### Specs

- Leon version:  leon@1.0.0-beta.3
- OS (or browser) version: Windows 10 
- Node.js version: 12.16.1
- Complete "npm run check" output: 

.: ASR :.

➡ Encoding WebM file to WAVE file...
✔ Encoding done
➡ Parsing WAVE file...
C:\Users\Utilisateur\Desktop\leon\leondevelop\server\dist\stt\stt.js:99
      this.parser.default.parse(buffer, data => {
                          ^

TypeError: Cannot read property 'parse' of undefined
    at Stt.parse (C:\Users\Utilisateur\Desktop\leon\leondevelop\server\dist\stt\stt.js:99:27)
    at FfmpegCommand.<anonymous> (C:\Users\Utilisateur\Desktop\leon\leondevelop\server\dist\core\asr.js:74:17)
    at FfmpegCommand.emit (events.js:311:20)
    at emitEnd (C:\Users\Utilisateur\Desktop\leon\leondevelop\node_modules\fluent-ffmpeg\lib\processor.js:426:16)
    at endCB (C:\Users\Utilisateur\Desktop\leon\leondevelop\node_modules\fluent-ffmpeg\lib\processor.js:587:15)
    at handleExit (C:\Users\Utilisateur\Desktop\leon\leondevelop\node_modules\fluent-ffmpeg\lib\processor.js:170:11)
    at ChildProcess.<anonymous> (C:\Users\Utilisateur\Desktop\leon\leondevelop\node_modules\fluent-ffmpeg\lib\processor.js:184:11)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.3 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utilisateur\AppData\Roaming\npm-cache\_logs\2020-03-23T14_33_03_805Z-debug.log

C:\Users\Utilisateur\Desktop\leon\leondevelop>npm start

> leon@1.0.0-beta.3 start C:\Users\Utilisateur\Desktop\leon\leondevelop
> cross-env LEON_NODE_ENV=production node ./server/dist/index.js

______________________________________________________________________________________________________
############################################################################# 
______________________________________________________________________________________________________

.: LEON :.

➡ Talking...
C:\Users\Utilisateur\Desktop\leon\leondevelop\server\dist\tts\tts.js:75
    this.synthesizer.default.save(speech.text, this.em, (file, duration) => {
                             ^

TypeError: Cannot read property 'save' of undefined
    at Tts.forward (C:\Users\Utilisateur\Desktop\leon\leondevelop\server\dist\tts\tts.js:75:30)
    at Tts.add (C:\Users\Utilisateur\Desktop\leon\leondevelop\server\dist\tts\tts.js:136:12)
    at Brain.talk (C:\Users\Utilisateur\Desktop\leon\leondevelop\server\dist\core\brain.js:75:18)
    at Socket.<anonymous> (C:\Users\Utilisateur\Desktop\leon\leondevelop\server\dist\core\brain.js:209:18)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.3 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utilisateur\AppData\Roaming\npm-cache\_logs\2020-03-23T14_35_08_177Z-debug.log
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon package version:

### Extra (like a sample repo to reproduce the issue, etc.)

- When I talk to Leon saying "Hello" for example the first error occurs.
- When I write him "Hello" the second error occurs.
Each time it's an error with either STT or TTS.

**Comment by Divlo** [comment]
Could you please try with the latest version of the `develop` branch ?
Also there is now Gitpod, so you can easily start Leon directly in your browser, it is worth taking a look: https://gitpod.io/#https://github.com/leon-ai/leon
