### ISSUE TITLE
Cannot find module server/dist/index.js

### ISSUE THREAD

**Issue by iobreaker** [leon-ai/leon#185]
Hi Team,

I have just deployed a fresh installation of lean using the hwoto 

```
git clone -b master https://github.com/leon-ai/leon.git leon
```
All build phase worked well (only a problem with pipenv and python3.6) i resolved.

After the build :

```
$ npm run check

> leon@1.0.0-beta.2 check /home/ted/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

 /bin/sh -c node --version
✔ v10.19.0

 /bin/sh -c npm --version
✔ 6.14.4

 /bin/sh -c pipenv --version
✔ pipenv, version 11.9.0

 /bin/sh -c pipenv --where
✔ /home/ted/leon/bridges/python

 /bin/sh -c pipenv run python --version
✔ Python 3.6.10

 /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 31, "options": {}}}

 Classifier state
✔ Found and valid

 Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

 Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

 Watson TTS
❗ Watson TTS is not yet configured

 Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

 Watson STT
❗ Watson STT is not yet configured

 Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

 Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
```

But when running **npm start** I have this error

```
$ npm start

> leon@1.0.0-beta.2 start /home/ted/leon
> cross-env LEON_NODE_ENV=production node ./server/dist/index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/ted/leon/server/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.2 start: `cross-env LEON_NODE_ENV=production node ./server/dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leon@1.0.0-beta.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ted/.npm/_logs/2020-05-14T13_37_07_542Z-debug.log
```

### Specs

- Leon version: latest stable
- npm version : 6.14.4
- Node.js version: v10.19.0
- Complete "npm run check" output:

### Expected Behavior

starting leon

### Actual Behavior

ERROR : cross-env LEON_NODE_ENV=production node ./server/dist/index.js

- serve directory content 👍 

```
~/leon$ ll ./server/
total 12
drwxrwxr-x  3 ted ted 4096 May 14 12:32 ./
drwxrwxr-x 17 ted ted 4096 May 14 13:36 ../
drwxrwxr-x 11 ted ted 4096 May 14 12:32 src/
```

Regards

**Comment by iobreaker** [comment]
Ok i found the mistake

must run **npm run build** before

Thanks
