### ISSUE TITLE
Build error with npm install

### ISSUE THREAD

**Issue by yanickrochon** [leon-ai/leon#187]
### Specs

- Leon version: 1.0.0-beta.2
- OS (or browser) version: Ubuntu Server 20.04
- Node.js version: v12.16.3
- Complete "npm run check" output:

```
$ npm run check

> leon@1.0.0-beta.2 check /home/thermo/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

✖ Error: Command failed: /bin/sh -c pipenv --version
/bin/sh: 1: pipenv: not found


    at makeError (/home/thermo/leon/node_modules/execa/index.js:172:9)
    at /home/thermo/leon/node_modules/execa/index.js:277:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 2)
    at /home/thermo/leon/scripts/check.js:43:6 {
  code: 127,
  stdout: '',
  stderr: '/bin/sh: 1: pipenv: not found\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c pipenv --version',
  timedOut: false,
  killed: false
}
```

### Expected Behavior

To install dependencies successfully

### Actual Behavior

Not installing dependencies successfully.

### How Do We Reproduce?

* Fresh install of Ubuntu Server 20.04
* Installing Node v12 through `nvm`
* Updating `npm`
* Installing `build-essential`, Python3 with `venv`.
* Cloning repository
* Running `npm i`

### Extra Error output

```
$ npm i

> leon@1.0.0-beta.2 preinstall /home/thermo/leon
> node scripts/setup/preinstall.js

➡ Running Leon's installation...

> grpc@1.18.0 install /home/thermo/leon/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.18.0/node-v72-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.18.0 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/thermo/leon/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  ...
  [bunch of files]
  ...
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_plugin.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.o
../deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc: In function ‘grpc_error* try_http_parsing(grpc_chttp2_transport*)’:
../deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:2457:40: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘grpc_http_response’ {aka ‘struct grpc_http_response’}; use assignment or value-initialization instead [-Werror=class-memaccess]
 2457 |   memset(&response, 0, sizeof(response));
      |                                        ^
In file included from ../deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:44:
../deps/grpc/src/core/lib/http/parser.h:71:16: note: ‘grpc_http_response’ {aka ‘struct grpc_http_response’} declared here
   71 | typedef struct grpc_http_response {
      |                ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [grpc.target.mk:493: Release/obj.target/grpc/deps/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.o] Error 1
make: Leaving directory '/home/thermo/leon/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/thermo/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-31-generic
gyp ERR! command "/home/thermo/.nvm/versions/node/v12.16.3/bin/node" "/home/thermo/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/thermo/leon/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/thermo/leon/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/thermo/leon/node_modules/grpc
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/thermo/.nvm/versions/node/v12.16.3/bin/node /home/thermo/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/thermo/leon/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/thermo/leon/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/thermo/leon/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.4.0-31-generic
node-pre-gyp ERR! command "/home/thermo/.nvm/versions/node/v12.16.3/bin/node" "/home/thermo/leon/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/thermo/leon/node_modules/grpc
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/thermo/.nvm/versions/node/v12.16.3/bin/node /home/thermo/.nvm/versions/node/v12.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/thermo/leon/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/thermo/leon/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@11.3.2 requires a peer of eslint@^3.19.0 || ^4.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN regexpp2@1.1.2 requires a peer of dts-bundle@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN ts-enum-util@3.1.0 requires a peer of typescript@>= 2.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-x64@4.1.0 (node_modules/@ffmpeg-installer/darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-x64@4.1.0 (node_modules/@ffmpeg-installer/win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-x64@4.1.0: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules/@ffmpeg-installer/win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules/@ffmpeg-installer/linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/win32-ia32@4.0.2 (node_modules/@ffprobe-installer/win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/win32-ia32@4.0.2: wanted {"os":"win32","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/darwin-x64@4.0.3 (node_modules/@ffprobe-installer/darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/darwin-x64@4.0.3: wanted {"os":"darwin","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/win32-x64@4.0.2 (node_modules/@ffprobe-installer/win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/win32-x64@4.0.2: wanted {"os":"win32","arch":"x64"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-ia32@4.0.3 (node_modules/@ffprobe-installer/linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-ia32@4.0.3: wanted {"os":"linux","arch":"ia32"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.18.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thermo/.npm/_logs/2020-05-25T21_00_51_670Z-debug.log

**Comment by louistiti** [comment]
Hello @yanickrochon,

Thanks for opening this issue.

It seems Pipenv is not installed on your system, please follow the [instructions here](https://docs.getleon.ai/how-to/#how-to-install-pipenv) and let me know if that helps.

**Comment by yanickrochon** [comment]
Installing `pipenv` with `venv`, gotta love Python.

However, now running `npm run check` returns other errors :

```
➡ /bin/sh -c node --version
✔ v12.16.3

➡ /bin/sh -c npm --version
✔ 6.14.5

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /home/thermo/leon

➡ /bin/sh -c pipenv run python --version
✖ Python 3.8.2
The Python version must be 3.6.x. Please install it: https://www.python.org/downloads

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Warning: There was an unexpected error while activating your virtualenv. Continuing anyway...
Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "/home/thermo/leon/bridges/python/utils.py", line 10, in <module>
    from tinydb import TinyDB, Query, operations
ModuleNotFoundError: No module named 'tinydb'
```

So, I really need to downgrade from Python 3.8 to Python 3.6? is Leon _that_ picky?

**Comment by yanickrochon** [comment]
I was expecting a docker image to actually exist already, not to clone this repo, install all dependencies and build it myself. What's the point of having docker is it's an extra step?

**Comment by louistiti** [comment]
It seems you are using the `master` branch.

Please try to pull Leon with the default branch (the `develop` one). I still did not merge the changes into `master`.

Let me know if that helps.

**Comment by yanickrochon** [comment]
WIth the `develop` branch, the build seems to be successful, however everything I write yields an error with some module :

![image](https://user-images.githubusercontent.com/78461/83147292-7c24a800-a0c5-11ea-8315-220bfb765de4.png)

**Comment by yanickrochon** [comment]
I was asked to put this on the side for the time being, so I'll close this since the error is issue is now irrelevant to this one.
