### ISSUE TITLE
TypeError: DeepSpeech.Model is not a constructor

### ISSUE THREAD

**Issue by varunsrivatsa** [leon-ai/leon#328]
Hey Louis, I recently came across your awesome project and really wanted to try it out. But I ran into this deepspeech error which I can't figure out.  Can you please look into it and help me out.

### Specs

- Leon version:1.0.0-beta.4
- OS (or browser) version: Ubuntu (checked on both VirtualBox and WSL2)
- Node.js version: v16.13.1
- Complete "npm run check" output:
```
> leon@1.0.0-beta.4 check
> babel-node scripts/run-check.js

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
⠋
---

.: CHECKING :.

➡ node --version
✔ v16.13.1

➡ npm --version
✔ 8.1.2

➡ pipenv --version
✔ pipenv, version 2021.11.23

➡ pipenv --where
✔ /home/varun/projects/leon/bridges/python

➡ pipenv run python --version
✔ Python 3.8.10

➡ pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 69, "options": {}}}

➡ NLP model state
✔ Found and valid

➡ Amazon Polly TTS
✔ Configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
✔ Found Flite at bin/flite/flite

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
✔ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
✔ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured 
```

### Expected Behavior

I wanted to try the offline configuration. 
The TTS_Provider is working fine, there isn't any problem with that. (except the voice🙄). But I have some issues with the STT_Provider (deepspeech). I'm getting the following error output, whenever I open localhost after `npm start`.

### Actual Behavior
```
> leon@1.0.0-beta.4 start
> cross-env LEON_NODE_ENV=production node ./server/dist/index.js


---

.: INITIALIZATION :.

✔ The current env is production
✔ The current version is 1.0.0-beta.4
✔ The current language is en-US
✔ The current time zone is Asia/Calcutta
✔ Collaborative logger enabled
✔ Server is available at http://localhost:1337

---

.: REQUESTING :.

➡ GET /

---

.: REQUESTING :.

➡ GET /assets/index.10acce3d.js

---

.: REQUESTING :.

➡ GET /assets/vendor.fb5407a4.js

---

.: REQUESTING :.

➡ GET /assets/index.77f1e308.css

---

.: REQUESTING :.

➡ GET /assets/mic.d8267246.svg

---

.: REQUESTING :.

➡ GET /assets/logo.0679f287.svg

---

.: REQUESTING :.

➡ GET /v1/info

---

.: GET /INFO :.

✔ Information pulled.

---

.: CLIENT :.

✔ Connected
➡ Type: webapp
➡ Socket id: BTDbrHJSD5p2pk1PAAAB

---

.: BRAIN :.

✔ New instance

---

.: TTS :.

✔ New instance
➡ Initializing TTS...

---

.: FLITE SYNTHESIZER :.

✔ Synthesizer initialized

---

.: TTS :.

✔ TTS initialized

---

.: NER :.

✔ New instance

---

.: NLU :.

✔ New instance

---

.: ASR :.

✔ New instance

---

.: STT :.

✔ New instance
➡ Initializing STT...

---

.: DEEPSPEECH PARSER :.

➡ GPU version not found, trying to get the CPU version...
✖ No DeepSpeech library found:
GPU: Error: Cannot find module 'deepspeech-gpu'
Require stack:
- /home/varun/projects/leon/server/dist/stt/deepspeech/parser.js
- /home/varun/projects/leon/server/dist/stt/stt.js
- /home/varun/projects/leon/server/dist/core/server.js
- /home/varun/projects/leon/server/dist/index.js
CPU: Error: Cannot find module '/home/varun/projects/leon/node_modules/deepspeech/lib/binding/v0.9.3/linux-x64/node-v93/deepspeech.node'
Require stack:
- /home/varun/projects/leon/node_modules/deepspeech/index.js
- /home/varun/projects/leon/server/dist/stt/deepspeech/parser.js
- /home/varun/projects/leon/server/dist/stt/stt.js
- /home/varun/projects/leon/server/dist/core/server.js
- /home/varun/projects/leon/server/dist/index.js
➡ Loading model from file bin/deepspeech/deepspeech.pbmm...
/home/varun/projects/leon/server/dist/stt/deepspeech/parser.js:75
    model = new DeepSpeech.Model(args.model);
            ^

TypeError: DeepSpeech.Model is not a constructor
    at Object.parser.init (/home/varun/projects/leon/server/dist/stt/deepspeech/parser.js:75:13)
    at Stt.init (/home/varun/projects/leon/server/dist/stt/stt.js:55:27)
    at Socket.<anonymous> (/home/varun/projects/leon/server/dist/core/server.js:163:20)
    at Socket.emit (node:events:390:28)
    at Socket.emitUntyped (/home/varun/projects/leon/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/varun/projects/leon/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
### Extra (like a sample repo to reproduce the issue, etc.)
I believe I should fix this 👇
```
➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"
```

**Comment by NXture** [comment]
You are using node v16, which isn't supported by deepspeech. Mozilla discontinued it's development and  i don't think if it will ever get any support for node v16 or any other latest versions.

if you still want to use deepspeech STT, downgrade your node version to v14, it'll work.

**Comment by varunsrivatsa** [comment]
Understood, thanks for your support @NXture
