### ISSUE TITLE
Unable to install it in ubuntu 18.10

### ISSUE THREAD

**Issue by menporulporiayalan** [leon-ai/leon#36]
**Specs** 

- Leon version: commit    d0ca87d
- pipenv version - 2018.11.26
- npm version - 5.8.0
- python version - 3.6.7
- OS  - Ubuntu 18.10

**Expected Behaviour**
Leon Should build successfully

**Actual Behaviour**
Throwed an error While installing the python package 

**Error Message**
✖ Failed to install the Python packages: Error: Command failed: /bin/sh -c pipenv install

Any help would be appreciated.

**Comment by louistiti** [comment]
Hello @menporulporiayalan,

Thanks for opening this issue. Could you please use [this issue template](https://raw.githubusercontent.com/leon-ai/leon/develop/.github/ISSUE_TEMPLATE/BUG.md) to have a better understanding of the problem you are facing to?

**Comment by menporulporiayalan** [comment]
@louistiti  thanks, I have updated the python again and generated but still the same.

**Comment by nto4** [comment]
Npm verision is 3x update it 8x


22 Şub 2019 Cum 08:04 tarihinde menporulporiayalan <notifications@github.com>
şunu yazdı:

**Comment by louistiti** [comment]
@menporulporiayalan, please paste the full content of your `npm run check`.

**Comment by menporulporiayalan** [comment]
@louistiti  I got this message. 

```
npm ERR! path /home/emperoreby/sideprojects/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/emperoreby/sideprojects/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emperoreby/.npm/_logs/2019-02-22T13_34_33_959Z-debug.log

```

**Comment by louistiti** [comment]
As the error mentions: `This is related to npm not being able to find a file`.

1. Are you sure you correctly upgraded to npm >= `5`? (try maybe to see with a `npm --version`)
2. Are you sure you are in the right path? According to your current path `/home/emperoreby/sideprojects/package.json` I'm wondering if you should not be in a path like `/home/emperoreby/sideprojects/leon/package.json`

If 1. and 2. does not match the issue, then:
1. Clean npm cache: `npm cache clean`
2. Update npm `sudo npm install -g npm@latest`
3. Retry `npm install`

**Comment by menporulporiayalan** [comment]
Yes, I am sorry. I ran the `npm run check` in different path. Here is the error content 
```

> leon@1.0.0-beta.0 check /home/emperoreby/sideprojects/leon
> babel-node scripts/run-check.js

⠋
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.10.0

➡ /bin/sh -c npm --version
✔ 6.8.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

✖ Error: Command failed: /bin/sh -c pipenv run python --version
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli/command.py", line 408, in run
    command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 2310, in do_run
    three=three, python=python, validate=False, pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 574, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 494, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 350, in find_a_system_python
    from .vendor.pythonfinder import Finder
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/__init__.py", line 14, in <module>
    from .pythonfinder import Finder
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 6, in <module>
    from .models import SystemPath
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/__init__.py", line 11, in <module>
    from ..utils import KNOWN_EXTS, unnest
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/utils.py", line 27, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```

**Comment by menporulporiayalan** [comment]
@louistiti  Never Mind! I have installed with the docker :+1:  As I installed successfully I am closing this issue.

**Comment by benonilearns** [comment]
So i had this issue as well and wanted to provide a solution. This error occurs when you install pip/pipenv in a way that your pip and pipenv installation goes nuts(PATH issues). First: 

sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall
sudo python -m pip uninstall pip && sudo apt install python3-pip --reinstall

Then follow this guide step by step: 

https://phoikoi.io/2018/04/03/bootstrap-pipenv-debian.html

Note: If you're on ubuntu modify .bashrc not bash_profile. 

Lastly:

cd leon (wherever you cloned it)
pipenv --python 3.6.7
npm install
npm run check
npm run build
npm run

Then navigate to localhost:1337 in your browser. 

Moral of the story: Never _pip install pipenv_. Use **python3 -m pip install --user pipenv**.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [📝 FAQ in docs](https://trello.com/c/NwWLpufW/240-%F0%9F%93%9D-faq-in-docs)

**Comment by louistiti** [comment]
Hello @benonilearns,

Thanks for that. Your solve will be added to the FAQ once it'll be there.

**Comment by menporulporiayalan** [comment]
Thanks mate! @benonilearns
