### ISSUE TITLE
Add a tutorial to install on a Raspberry Pi

### ISSUE THREAD

**Issue by borisrorsvort** [leon-ai/leon#37]
### Documentation Is:
- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Explanation

I guess the ideal setup would be to install it on a raspberry pi or similar board, make it listen in the current room, and plug it to your favorite speakers.

### Proposal

It might be nice to add some tutorial about small boards install.

**Comment by louistiti** [comment]
Hello @borisrorsvort,

Thanks for suggesting, and yes, I plan to create such contents later on.

However, if you want to get your hands dirty and do it, then you are more than welcome 😉

**Comment by Sab94** [comment]
@louistiti, can I hijack this one?? 😅😅

**Comment by louistiti** [comment]
Hello @Sab94,

Yes with pleasure! Let us know once you have something.

**Comment by Thibaud-A** [comment]
Hello,

I tried to do it on my own but unfortunatly I got this error :
![image](https://user-images.githubusercontent.com/7150373/53687971-65659900-3d3c-11e9-941e-e18aa5ffaec7.png)
If you get the way to fix it by loading another library it could interrested me ;-) 
I'm on a Pi 2 B.

**Comment by mbwhite** [comment]
I've started on some notes here... 
https://gist.github.com/mbwhite/2de7326d4680591101a27a53315a11b8

At present though I want to learn more about how Leon is working on vanilla ubuntu before heading back to the PI.

**Comment by Shrubhog** [comment]
I have an older Raspberry Pi to test this on, and I could test it once I get back from traveling at the moment. I had a newer Pi 3, like @mbwhite's but I broke an I/O component while testing the GPIO pins.

**Comment by louistiti** [comment]
Nice! Looking forward to see that then.
I'll also need to jump into that topic later on.

Enjoy your trip! 😄

**Comment by kominoshja** [comment]
I'm planning to write a blog about installing Leon on Ubuntu 18.04 if that helps anyone

**Comment by Shrubhog** [comment]
@kominoshja, as I always run into one error and another, It'd be much appreciated. Thanks!

**Comment by louistiti** [comment]
@kominoshja awesome, let us know once you are done with it, I'll add the blog post link to the [How-To](https://docs.getleon.ai/how-to) section of the docs.

@Shrubhog oh really, do not hesitate to open issues then 😉

**Comment by Shrubhog** [comment]
I have started building and installing Leon's dependencies. My notes can be found [here](https://gist.github.com/Shrubhog/12c5fdd7da6aca8758c2c21ae61f5443). I have also diagnosed the issue with the Pi 3 and might fix it and test Leon there as well.

**Comment by Shrubhog** [comment]
I will clone the `latest` branch first.

**Comment by Shrubhog** [comment]
It seems my Pi does not have enough space to support it right now. I'll try deleting some other files later.

**Comment by louistiti** [comment]
Hello @Shrubhog,

Alright, thanks for keeping us updated and for handling it!

**Comment by SodaLover** [comment]
Currently working on it, doing a log on all the steps for a possible readme.

**Comment by shashwataggarwal** [comment]
@borisrorsvort @louistiti is this issue still open?

**Comment by louistiti** [comment]
Yes it is. I'm taking my time on my current project but will come back to work on Leon later on for sure 😉

**Comment by Tejaswgupta** [comment]
I see that it is not assigned to anyone . can I work on this.

**Comment by louistiti** [comment]
Sure you can work on it. I'll need to also take a look at it once I'll be back.

**Comment by Tetsujinfr** [comment]
Hi
did anyone managed to get it working on RPI?
I did sudo install all the dependencies without issues.
I am trying to install it on the Jetson NX, I have have some mysterious errors during the SUDO NPM INSTALL:

> ...
> CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/wrap_memcpy.o
>   CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gprpp/fork.o
>   CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gprpp/thd_posix.o
>   CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gprpp/thd_windows.o
>   CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/profiling/basic_timers.o
>   CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/profiling/stap_timers.o
>   AR(target) Release/obj.target/libgpr.a
>   COPY Release/libgpr.a
>   CXX(target) Release/obj.target/grpc_node/ext/byte_buffer.o
> In file included from ../../nan/nan_new.h:189:0,
>                  from ../../nan/nan.h:223,
>                  from ../ext/byte_buffer.cc:21:
> ../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
> ../../nan/nan_implementation_12_inl.h:356:37: **error**: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
>    return v8::StringObject::New(value).As<v8::StringObject>();
>                                      ^
> In file included from /home/tetsfr/.cache/node-gyp/12.17.0/include/node/node.h:67:0,
>                  from ../../nan/nan.h:53,
>                  from ../ext/byte_buffer.cc:21:
> /home/tetsfr/.cache/node-gyp/12.17.0/include/node/v8.h:5531:23: note: candidate: static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)
>    static Local<Value> New(Isolate* isolate, Local<String> value);
>                        ^~~
> /home/tetsfr/.cache/node-gyp/12.17.0/include/node/v8.h:5531:23: note:   candidate expects 2 arguments, 1 provided
> In file included from ../../nan/nan_new.h:189:0,
>                  from ../../nan/nan.h:223,
>                  from ../ext/byte_buffer.cc:21:
> ../../nan/nan_implementation_12_inl.h:356:58: error: expected primary-expression before ‘>’ token
>    return v8::StringObject::New(value).As<v8::StringObject>();
>                                                           ^
> ../../nan/nan_implementation_12_inl.h:356:60: error: expected primary-expression before ‘)’ token
>    return v8::StringObject::New(value).As<v8::StringObject>();
>                                                             ^
> grpc_node.target.mk:186: recipe for target 'Release/obj.target/grpc_node/ext/byte_buffer.o' failed
> make: *** [Release/obj.target/grpc_node/ext/byte_buffer.o] Error 1
> make: Leaving directory '/media/tetsfr/SSD/leon/node_modules/grpc/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR! System Linux 4.9.140-tegra
> ...
> 

Not sure where this one comes from? the compilation did start ok and ran fine for like 5 mins and then crashed. seems to be related to some strig function compile error on arm8 (Jetson NX cpu), not 100% sure though.

thanks for your help on this.

**Comment by Guillaume-Syc** [comment]
Hi @Tetsujinfr,
I don't know if you're still interest, but I manage to install Leon on a raspberry pi 3B+ by following standard instruction. I try to do it for 3 mouths and with nodejs version 14, it work !! Apparently some modification have been done a few days ago may be it thanks that ;)

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 Compatibility with ARM architectures and test on Pis](https://trello.com/c/CxRNbLHQ/256-%F0%9F%94%A7-compatibility-with-arm-architectures-and-test-on-pis)

**Comment by louistiti** [comment]
> Hi @Tetsujinfr,
> I don't know if you're still interest, but I manage to install Leon on a raspberry pi 3B+ by following standard instruction. I try to do it for 3 mouths and with nodejs version 14, it work !! Apparently some modification have been done a few days ago may be it thanks that ;)

That is a good news! Thanks for letting us know.

**Comment by louistiti** [comment]
Hi, this month we have been working on compiling all Python stuff related upfront. Meaning, Leon does not need Python at runtime anymore.

Please try the three following commands and let's see how it goes and paste the report URL:

```bash
# Install the beta version of the Leon CLI
npm install --global @leon-ai/cli@beta

# Create a Leon instance based on the develop GitHub branch
leon create birth --develop

# Create a report
leon check
```
