### ISSUE TITLE
npm run setup:offline is not working

### ISSUE THREAD

**Issue by opeth646** [leon-ai/leon#374]
### Specs

- Leon version: 1.1.2
- OS (or browser) version: Raspbian Buster
- Node.js version: v16.15.0
- Complete "leon check" (or "npm run check") output:
- npm run check

> leon@1.0.0-beta.7+dev check
> babel-node scripts/run-check.js

⠋

.: CHECKING :.
➡ node --version
✔ v16.15.0

➡ npm --version
✔ 8.5.5

➡ pipenv --version
✔ pipenv, version 2022.5.2

➡ pipenv --where
✔ /home/pi/leon/bridges/python

➡ pipenv run python --version
✔ Python 3.9.2

➡ pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 77, "options": {}}}

➡ NLP model state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
✔ Found Flite at bin/flite/flite

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
✔ Found Coqui language model at bin/coqui/huge-vocabulary.scorer

.: REPORT :.
➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
✔ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
✔ Offline speech-to-text

✔ Hooray! Leon can run correctly

### Expected Behavior
snowboy installed

### Actual Behavior
npm run setup:offline-hotword

> leon@1.0.0-beta.7+dev setup:offline-hotword
> babel-node scripts/setup-offline/run-setup-hotword.js

➡ Setting up offline hotword detection...
➡ Installing dependencies...
➡ Executing the following command: sudo apt-get install sox libsox-fmt-all -y
✔ System dependencies downloaded
➡ Installing hotword dependencies...
✔ Offline hotword detection installed
✖ Failed to install offline hotword detection: Error: Command failed with exit code 1: cd hotword/node_modules/@bugsounet/snowboy && CXXFLAGS="--std=c++17" ../../../node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp clean configure build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.8
node-pre-gyp info using node@16.15.0 | linux | arm
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.0 | linux | arm
gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/16.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/16.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/16.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [snowboy.target.mk:149: Release/obj.target/snowboy.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.32-v7l+
gyp ERR! command "/home/pi/.config/nvm/versions/node/v16.15.0/bin/node" "/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /home/pi/leon/hotword/node_modules/@bugsounet/snowboy
gyp ERR! node -v v16.15.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/pi/.config/nvm/versions/node/v16.15.0/bin/node /home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/leon/hotword/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 5.15.32-v7l+
node-pre-gyp ERR! command "/home/pi/.config/nvm/versions/node/v16.15.0/bin/node" "/home/pi/leon/hotword/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "clean" "configure" "build"
node-pre-gyp ERR! cwd /home/pi/leon/hotword/node_modules/@bugsounet/snowboy
node-pre-gyp ERR! node -v v16.15.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
make: Entering directory '/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/build'
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
make: Leaving directory '/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/build'
Failed to execute '/home/pi/.config/nvm/versions/node/v16.15.0/bin/node /home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
✖ Failed to setup offline hotword: Error: Command failed with exit code 1: cd hotword/node_modules/@bugsounet/snowboy && CXXFLAGS="--std=c++17" ../../../node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp clean configure build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.8
node-pre-gyp info using node@16.15.0 | linux | arm
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.0 | linux | arm
gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/16.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/16.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/16.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.0 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [snowboy.target.mk:149: Release/obj.target/snowboy.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.32-v7l+
gyp ERR! command "/home/pi/.config/nvm/versions/node/v16.15.0/bin/node" "/home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /home/pi/leon/hotword/node_modules/@bugsounet/snowboy
gyp ERR! node -v v16.15.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/pi/.config/nvm/versions/node/v16.15.0/bin/node /home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/leon/hotword/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 5.15.32-v7l+
node-pre-gyp ERR! command "/home/pi/.config/nvm/versions/node/v16.15.0/bin/node" "/home/pi/leon/hotword/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "clean" "configure" "build"
node-pre-gyp ERR! cwd /home/pi/leon/hotword/node_modules/@bugsounet/snowboy
node-pre-gyp ERR! node -v v16.15.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
make: Entering directory '/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/build'
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
make: Leaving directory '/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/build'
Failed to execute '/home/pi/.config/nvm/versions/node/v16.15.0/bin/node /home/pi/.config/nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-arm --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)

**Comment by superfino** [comment]
Same problem here with Bullseye on a Pi 2B+

I don't know if this is exactly the same problem and root cause but it looks very similar.

Any comment?


[errors.log](https://github.com/leon-ai/leon/files/8968743/errors.log)

**Comment by MoonlightGriffon** [comment]
I'm also having a similar problem while running it with a docker context. From what I can tell this is the same issue but on different architectures with the only noticeable differences, version numbers and paths aside, being on line 133. In case it helps, here's my terminal logs of this issue. I was using a docker environment when this happened. 

gitpod /workspace/leon (develop) $ npm run setup:offline-hotword

> leon@1.0.0-beta.7+dev setup:offline-hotword
> babel-node scripts/setup-offline/run-setup-hotword.js

ℹ️  Setting up offline hotword detection...
ℹ️  Installing dependencies...
ℹ️  Executing the following command: sudo apt-get install sox libsox-fmt-all -y
✅ System dependencies downloaded
ℹ️  Installing hotword dependencies...
✅ Offline hotword detection installed
🚨 Failed to install offline hotword detection: Error: Command failed with exit code 1: cd hotword/node_modules/@bugsounet/snowboy && CXXFLAGS="--std=c++17" ../../../node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp clean configure build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.8
node-pre-gyp info using node@16.15.1 | linux | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.1 | linux | x64
gyp info find Python using Python version 3.8.13 found at "/home/gitpod/.pyenv/versions/3.8.13/bin/python3"
gyp info spawn /home/gitpod/.pyenv/versions/3.8.13/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/workspace/leon/hotword/node_modules/@bugsounet/snowboy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gitpod/.cache/node-gyp/16.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/gitpod/.cache/node-gyp/16.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/gitpod/.cache/node-gyp/16.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/workspace/leon/hotword/node_modules/@bugsounet/snowboy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.1 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [snowboy.target.mk:153: Release/obj.target/snowboy.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.16.20-051620-generic
gyp ERR! command "/home/gitpod/.nvm/versions/node/v16.15.1/bin/node" "/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /workspace/leon/hotword/node_modules/@bugsounet/snowboy
gyp ERR! node -v v16.15.1
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/gitpod/.nvm/versions/node/v16.15.1/bin/node /home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64/snowboy.node --module_name=snowboy --module_path=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/workspace/leon/hotword/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 5.16.20-051620-generic
node-pre-gyp ERR! command "/home/gitpod/.nvm/versions/node/v16.15.1/bin/node" "/workspace/leon/hotword/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "clean" "configure" "build"
node-pre-gyp ERR! cwd /workspace/leon/hotword/node_modules/@bugsounet/snowboy
node-pre-gyp ERR! node -v v16.15.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
make: Entering directory '/workspace/leon/hotword/node_modules/@bugsounet/snowboy/build'
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
make: Leaving directory '/workspace/leon/hotword/node_modules/@bugsounet/snowboy/build'
Failed to execute '/home/gitpod/.nvm/versions/node/v16.15.1/bin/node /home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64/snowboy.node --module_name=snowboy --module_path=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
🚨 Failed to setup offline hotword: Error: Command failed with exit code 1: cd hotword/node_modules/@bugsounet/snowboy && CXXFLAGS="--std=c++17" ../../../node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp clean configure build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.8
node-pre-gyp info using node@16.15.1 | linux | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.1 | linux | x64
gyp info find Python using Python version 3.8.13 found at "/home/gitpod/.pyenv/versions/3.8.13/bin/python3"
gyp info spawn /home/gitpod/.pyenv/versions/3.8.13/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/workspace/leon/hotword/node_modules/@bugsounet/snowboy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gitpod/.cache/node-gyp/16.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/gitpod/.cache/node-gyp/16.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/gitpod/.cache/node-gyp/16.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/workspace/leon/hotword/node_modules/@bugsounet/snowboy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.1 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [snowboy.target.mk:153: Release/obj.target/snowboy.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.16.20-051620-generic
gyp ERR! command "/home/gitpod/.nvm/versions/node/v16.15.1/bin/node" "/home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--module=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64/snowboy.node" "--module_name=snowboy" "--module_path=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /workspace/leon/hotword/node_modules/@bugsounet/snowboy
gyp ERR! node -v v16.15.1
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/gitpod/.nvm/versions/node/v16.15.1/bin/node /home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64/snowboy.node --module_name=snowboy --module_path=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/workspace/leon/hotword/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 5.16.20-051620-generic
node-pre-gyp ERR! command "/home/gitpod/.nvm/versions/node/v16.15.1/bin/node" "/workspace/leon/hotword/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "clean" "configure" "build"
node-pre-gyp ERR! cwd /workspace/leon/hotword/node_modules/@bugsounet/snowboy
node-pre-gyp ERR! node -v v16.15.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
make: Entering directory '/workspace/leon/hotword/node_modules/@bugsounet/snowboy/build'
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
make: Leaving directory '/workspace/leon/hotword/node_modules/@bugsounet/snowboy/build'
Failed to execute '/home/gitpod/.nvm/versions/node/v16.15.1/bin/node /home/gitpod/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64/snowboy.node --module_name=snowboy --module_path=/workspace/leon/hotword/node_modules/@bugsounet/snowboy/lib/node/binding/Release/node-v93-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
gitpod /workspace/leon (develop) $

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔧 [1.0.0] Compatibility with ARM architectures and GNU/Linux distributions](https://trello.com/c/CxRNbLHQ/256-%F0%9F%94%A7-100-compatibility-with-arm-architectures-and-gnu-linux-distributions)
