### ISSUE TITLE
/bin/sh: pipenv: command not found : Can't install pipenv on mac 

### ISSUE THREAD

**Issue by Antoinebr** [leon-ai/leon#4]
### Specs

- Leon version: latest ( 11-02-2019 )
- OS (or browser) version: MAC OS 10.13.6
- Node.js version: 10
- Complete "npm run check" output:

```
.: CHECKING :.
✖ Error: Command failed: /bin/sh -c pipenv --version
/bin/sh: pipenv: command not found
``` 

### Expected Behavior

Get Leon Installed 

### Actual Behavior

The Installation fails. 

### How Do We Reproduce?

Maybe specific to my machine and how Python is setup 

### Extra (like a sample repo to reproduce the issue, etc.)
```
pipenv 
command not found"

```
But : 
pip3 install pipenv says "Requirement already satisfied:" 

i created an alias ```alias pipenv="python3 -m pipenv"``` to get pipenv working but the install looks for pipenv in /bin/sh 

Any idea ? :p

**Comment by Antoinebr** [comment]
I followed this solution 

https://stackoverflow.com/questions/46391721/pipenv-command-not-found#answer-49842670 


now pipenv doesn't send "command not found" even without the alias but I added this to my .bash_profile 

```export PATH="$PATH:/usr/local/Cellar/python/3.7.0/bin"```

**Comment by louistiti** [comment]
Hello @Antoinebr,

Thanks for your issue. It seems to be a pipenv issue. I suppose you already followed this small section?

Moreover, please note that Leon runs with Python `3.6.x` today, and in your path you mentioned the version `3.7.0`.

**Comment by Antoinebr** [comment]
I started to write a Dockerfile to bypass this issue 

```
FROM mhart/alpine-node:10
WORKDIR /app
COPY . .

# Update & Install dependencies
RUN apk add --no-cache --update \
    git \
    bash \
    libffi-dev \
    openssl-dev \
    bzip2-dev \
    zlib-dev \
    readline-dev \
    sqlite-dev \
    build-base

RUN apk add linux-headers 

# Set Python version
ARG PYTHON_VERSION='3.6.0'
# Set pyenv home
ARG PYENV_HOME=/root/.pyenv


# Install pyenv, then install python versions
RUN git clone --depth 1 https://github.com/pyenv/pyenv.git $PYENV_HOME && \
    rm -rfv $PYENV_HOME/.git

ENV PATH $PYENV_HOME/shims:$PYENV_HOME/bin:$PATH

RUN pyenv install $PYTHON_VERSION
RUN pyenv global $PYTHON_VERSION
RUN pip install --upgrade pip && pyenv rehash
# Clean
RUN rm -rf ~/.cache/pip

RUN pip install pipenv

RUN npm rebuild
RUN npm install

CMD tail -f /dev/null
```


But ```npm run check``` throws new errors :


```
.: CHECKING :.

➡ /bin/sh -c node --version
✔ v10.13.0

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /app/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.0

➡ /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
✖ Error: Command failed: /bin/sh -c pipenv run python bridges/python/main.py en leon randomnumber "Give me a random number"
Traceback (most recent call last):
  File "bridges/python/main.py", line 4, in <module>
    import utils
  File "/app/bridges/python/utils.py", line 11, in <module>
    from tinydb import TinyDB, Query, operations
ModuleNotFoundError: No module named 'tinydb'



➡ Classifier state
✖ Classifier not found or broken. Try to generate a new one: "npm run train expressions"

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✖ Run modules
✖ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✖ Please fix the errors above

```

**Comment by louistiti** [comment]
It seems you don't have a [classifier](https://docs.getleon.ai/glossary.html#classifier). To solve this issue you need to run the training command: `npm run train expressions`.

I'll close that issue as you got Pipenv installed.
