### ISSUE TITLE
How to update the packages?

### ISSUE THREAD

**Issue by menporulporiayalan** [leon-ai/leon#44]
### How can I test my packages? 

I am trying to add some modules in the Existing package. I have added the quotes module in the leon package. 

I added this in` leon/data/expressions/en.json`
```

"quote": [
		"Tell me a Quote",
		"Give me a Quote",
	]
```
Then I have updated the below in ` leon/data/expressions/en.json
```

"quote":{ 
  	  "quotes":
  	   [
		  "Design is the silent ambassador of your brand. ",
		  "If there is one word I’d like to remove from any conversation about design, it’s “pretty.",
	   ]
    }
```

Then I create a new python file named  `quote.py`. Please see the below code. 

```
import utils

def quote(string):
	"""Leon says some quote"""

	return utils.output('end', 'quotes', utils.translate('quotes'))

```
I also created a new test python file in the test folder.  

But it seems it breaks leon. Wheneve I ask question it gives reply as "Sorry, I don't work correctly!"

How can I test the modules?  Do I need to add anything else?

**Comment by jtorresdev** [comment]
check the error logs get in console

**Comment by menporulporiayalan** [comment]
I am running it through docker. Can you please tell me the code to get the logs in console?

**Comment by jtorresdev** [comment]
`npm run dev:server`
`npm run dev:app`

**Comment by menporulporiayalan** [comment]
@jtorresdev  I got this below error when I tried  `npm run dev:server`

```

> leon@1.0.0-beta.1 dev:server /home/emperoreby/sideprojects/leon
> npm run train expressions && nodemon --watch server ./server/src/index.js --exec babel-node


> leon@1.0.0-beta.1 train /home/emperoreby/sideprojects/leon
> babel-node scripts/run-train.js "expressions"

sh: 1: babel-node: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! leon@1.0.0-beta.1 train: `babel-node scripts/run-train.js "expressions"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.1 train script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emperoreby/.npm/_logs/2019-02-27T02_45_26_860Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leon@1.0.0-beta.1 dev:server: `npm run train expressions && nodemon --watch server ./server/src/index.js --exec babel-node`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leon@1.0.0-beta.1 dev:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emperoreby/.npm/_logs/2019-02-27T02_45_26_870Z-debug.log

```

**Comment by jtorresdev** [comment]
@menporulporiayalan run `npm install`

**Comment by menporulporiayalan** [comment]
@jtorresdev  Got this error, while installing.
```

✖ Failed to install the Python packages: Error: Command failed: /bin/sh -c pipenv install
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1741, in do_install
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 574, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 494, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 350, in find_a_system_python
    from .vendor.pythonfinder import Finder
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/__init__.py", line 14, in <module>
    from .pythonfinder import Finder
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 6, in <module>
    from .models import SystemPath
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/__init__.py", line 11, in <module>
    from ..utils import KNOWN_EXTS, unnest
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/utils.py", line 27, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache


✖ Error: Command failed: /bin/sh -c pipenv install
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1741, in do_install
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 574, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 494, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 350, in find_a_system_python
    from .vendor.pythonfinder import Finder
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/__init__.py", line 14, in <module>
    from .pythonfinder import Finder
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 6, in <module>
    from .models import SystemPath
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/__init__.py", line 11, in <module>
    from ..utils import KNOWN_EXTS, unnest
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/utils.py", line 27, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```

**Comment by menporulporiayalan** [comment]
@louistiti  Could you please let me know what I did wrong? Why the Leon breaks?

**Comment by louistiti** [comment]
Hello @menporulporiayalan,

First of all, thanks for contributing by creating a Leon's module.

It's normal you have these errors as you are using Python 2.7 outside of Docker.
Try to do a `docker logs -f <CONTAINER>`, with the ID of your running container, that will show you a log in real time.

**Comment by menporulporiayalan** [comment]
@louistiti  In the Logs, I have got this below error. 

`✖ The expressions classifier is missing, please rebuild the project or if you are in dev run: npm run train expressions
`

**Comment by louistiti** [comment]
To develop a Leon's module, I do not recommend you to use Docker, as the Dockerfile and the npm scripts were prepared for an "easy to go" setup.
For the moment, the best shot would be to install Leon as mentioned in the documentation without Docker. To do so, you firstly need to use Python `3.6.x` as your machine is using Python `2.7` according to your previous log messages.

But now, to have a better understanding of the situation, please:

1. Run: `npm run docker:build`
2. Run: `npm run docker:run`
3. Run: `docker logs -f <YOUR_CONTAINER>`
4. Paste the full output of your terminal in a [Pastebin](https://pastebin.com/)
5. Share this Pastebin here

**Comment by menporulporiayalan** [comment]
@louistiti  Here it is ->  [Pastebin link](https://pastebin.com/y9ftieKM)

**Comment by louistiti** [comment]
The Pastebin is private, I cannot see it. Please switch to public.

**Comment by menporulporiayalan** [comment]
I am sorry, Kindly check now.

**Comment by louistiti** [comment]
Are you sure you built again with `npm run docker:build`? Because it should generate your classifier on that moment.

But as I said, don't use Docker for development purposes as the Leon's workflow is not ready for that (yet).

**Comment by menporulporiayalan** [comment]
Yes, I Built. I figured out the issue. The Issue is with the JSON file. Thanks for your time @louistiti :)
