### ISSUE TITLE
Unable to Install on Ubuntu 22.04 ( SyntaxError: Unexpected reserved word )

### ISSUE THREAD

**Issue by dipeshsingh253** [leon-ai/leon#440]
### Specs

- Leon version:
- OS (or browser) version:Ubuntu 22.04 LTS
- Node.js version:v16.18.0
- Complete "leon check" (or "npm run check") output: Error: You should have at least one instance.
- (if using Docker) Complete "npm run docker:check" output:
- (optional) Leon skill version:

### Expected Behavior:
Expected to installed properly and run

### Actual Behavior:
Unable to install

### How Do We Reproduce?
First I though this is because of older versions of node and npm but I am using latest version for them.
In sort my error and system details are availible in image given below.

![image](https://user-images.githubusercontent.com/84814627/195979252-820e345f-89b3-487c-a959-3abb0b49a1d7.png)

### Extra (like a sample repo to reproduce the issue, etc.)
sudo leon create birth
[sudo] password for dipesh253: 
file:///usr/local/lib/node_modules/@leon-ai/cli/build/index.js:13
await cli.runExit(arguments_, Cli.defaultContext);
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

Thanks for Your Help.

**Comment by louistiti** [comment]
@dipeshsingh253 hi, thanks for reporting. I'm moving this to the Leon CLI repository.
@Divlo any idea regarding this issue?
