### ISSUE TITLE
Python modules

### ISSUE THREAD

**Issue by guifelix** [leon-ai/leon#46]
I'm trying to create a new module/feature for leon but I'm having a hard time with 3rd party modules....
whenever I try to import a module I get the error:

```
✖ Traceback (most recent call last):
  File "bridges/python/main.py", line 23, in <module>
    main()
  File "bridges/python/main.py", line 18, in main
    m = import_module('packages.' + package + '.' + module)
  File "/home/gmaciel/docker/pessoal/leon/bridges/python/.venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./packages/dateandtime/saytime.py", line 45, in <module>
    import pyPEG
ModuleNotFoundError: No module named 'pyPEG'
```

Is there any steps I have to follow to get this done?
I already have pyPEG installed with "pip install pypeg2" and "pip3 install pypeg2" commands

**Comment by louistiti** [comment]
Hello @guifelix,

Thanks for creating a new Leon's module. If you share it, I'm looking forward to see the result.

Regarding your issue, you need to install the Python module via Pipenv from the `bridges/python` directory. Leon runs in a virtualenv which isolate his modules from the rest of your machine.
So:
1. `cd bridges/python`
2. `pipenv install pypeg2`
3. Import pyPEG in your module file

I will add it somewhere in the documentation.
Please let me know if it worked.

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [📝 [1.0.0-beta.2] How to install a Python module in the "Packages & Modules" section of the docs](https://trello.com/c/6IfPJaOm/237-%F0%9F%93%9D-100-beta2-how-to-install-a-python-module-in-the-packages-modules-section-of-the-docs)

**Comment by guifelix** [comment]
it worked!

**Comment by louistiti** [comment]
Awesome. I'll close this issue then.

Feel free to open another one if you have any other question.

**Comment by louistiti** [comment]
It'll be mentioned in the docs via this PR https://github.com/leon-ai/docs.getleon.ai/pull/6/commits/d5712485f6981759a7517b99604bbcf998feefe1.

**Comment by louistiti** [comment]
Done in https://github.com/leon-ai/docs.getleon.ai/commit/872189e4fc936850fa6d14e442c6738a34bfc1d9.
