### ISSUE TITLE
🚨 Failed to connect to the TCP server

### ISSUE THREAD

**Issue by Chard0212** [leon-ai/leon#480]
🚨 Failed to connect to the TCP server
ℹ️  Trying to connect to the TCP server...

**Comment by louistiti** [comment]
Please provide more information. Such as the report from the `leon check` command.

**Comment by xuguoliang1964** [comment]
When run "leon check" brings red message:"Cannot start TCP server:/bin/sh:1:tcp_server/dist/linux-x86_64/leon-tcp-server:not found"

**Comment by louistiti** [comment]
> When run "leon check" brings red message:"Cannot start TCP server:/bin/sh:1:tcp_server/dist/linux-x86_64/leon-tcp-server:not found"

Anything else? No report link?

**Comment by xuguoliang1964** [comment]
There is a zip file in the directory. When I unzip it, it reports:"End-of-central-directory signature not found....."

**Comment by xuguoliang1964** [comment]
There is a zip file in the directory. When I unzip it, it reports:"End-of-central-directory signature not found....."

> > When run "leon check" brings red message:"Cannot start TCP server:/bin/sh:1:tcp_server/dist/linux-x86_64/leon-tcp-server:not found"
> 
> Anything else? No report link?

There is a zip file in the directory. When I unzip it, it reports:"End-of-central-directory signature not found....."

**Comment by louistiti** [comment]
> There is a zip file in the directory. When I unzip it, it reports:"End-of-central-directory signature not found....."

You should not unzip it yourself, it is automatic during the setup process.

Please share a complete screenshot of the output from the `leon check` command.

**Comment by xuguoliang1964** [comment]
> End-o

> > There is a zip file in the directory. When I unzip it, it reports:"End-of-central-directory signature not found....."
> 
> You should not unzip it yourself, it is automatic during the setup process.
> 
> Please share a complete screenshot of the output from the `leon check` command.

![IMG_20230506_230311](https://user-images.githubusercontent.com/5945565/236632642-c2fdbef6-1a56-419a-a85a-103aaafe2ca5.jpg)

**Comment by louistiti** [comment]
1. How about the logs before that?
2. Does the process stop like this without any other info?

**Comment by xuguoliang1964** [comment]
The picture is the first screen by pipe with "less" command. I have another picture followed.
![IMG_20230506_232710](https://user-images.githubusercontent.com/5945565/236633330-50533f5f-42c4-40d7-9286-7c92ffa30c92.jpg)

**Comment by xuguoliang1964** [comment]
> 1. How about the logs before that?
> 2. Does the process stop like this without any other info?

When I run "leon create birth", everything is normal, no error message.

**Comment by louistiti** [comment]
Look at your report: https://report.getleon.ai/raw/exomuvuseg

It seems that you have less than 2 GB of total RAM. Leon needs at least ~ 4 GB. Also, I'm not sure about your disk space, but it may also be possible that the TCP server cannot be extracted properly because you don't have enough space there too.

**Comment by xuguoliang1964** [comment]
> Look at your report: https://report.getleon.ai/raw/exomuvuseg
> 
> It seems that you have less than 2 GB of total RAM. Leon needs at least ~ 4 GB. Also, I'm not sure about your disk space, but it may also be possible that the TCP server cannot be extracted properly because you don't have enough space there too.

Thank you. I am doing it again with a computer with Windows 10 and 16GB RAM.

**Comment by xuguoliang1964** [comment]
There is something wrong with my trial in window. 
When I run "leon create birth" ,it comes the screen followed.(https://report.getleon.ai/raw/vezoyamega)
![image](https://user-images.githubusercontent.com/5945565/236634160-7989223d-0ba0-4a71-8a58-210833a98044.png)

**Comment by xuguoliang1964** [comment]
> There is something wrong with my trial in window. When I run "leon create birth" ,it comes the screen followed. ![image](https://user-images.githubusercontent.com/5945565/236634160-7989223d-0ba0-4a71-8a58-210833a98044.png)

Here is screen with "leon check"
![image](https://user-images.githubusercontent.com/5945565/236634243-98807c19-56fa-4a85-b329-136b71f93b4d.png)

**Comment by louistiti** [comment]
Hi @xuguoliang1964,  I figured out the problem. As you can see from the error, Node.js returns a `ECONNRESET`, it means that the connection suddenly closed, so the Node.js bridge, TCP server and Python bridge cannot be downloaded. Hence, when you run Leon, Leon does not have them and can't run properly.

If I believe your screenshots, it seems that you are located in China. I've seen similar issue in the past. To fix it, try to change the location of your VPN so these binaries can correctly be downloaded.
Once you tried other VPN server, then do `leon delete`, then retry.

**Comment by Chard0212** [comment]
File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_vendor/urllib3/response.py", line 586, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/root/.pyenv/versions/3.9.10/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_vendor/urllib3/response.py", line 442, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pipenv.patched.pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

2023-06-06T17:31:54+03:00 - Failed to connect to the TCP server
2023-06-06T17:32:09+03:00 - Failed to connect to the TCP server
2023-06-06T17:32:27+03:00 - Failed to connect to the TCP server

**Comment by Chard0212** [comment]
node_modules/lodash.trimend
  @microsoft/recognizers-text-number  >=1.0.0-rc.30.0
  Depends on vulnerable versions of lodash.trimend
  node_modules/@microsoft/recognizers-text-number
    @microsoft/recognizers-text-date-time  >=1.0.0-rc.30.0
    Depends on vulnerable versions of @microsoft/recognizers-text-number
    Depends on vulnerable versions of @microsoft/recognizers-text-number-with-unit
    node_modules/@microsoft/recognizers-text-date-time
    @microsoft/recognizers-text-number-with-unit  >=1.0.0-rc.30.0
    Depends on vulnerable versions of @microsoft/recognizers-text-number
    node_modules/@microsoft/recognizers-text-number-with-unit
    @microsoft/recognizers-text-suite  >=1.0.0-rc.30.0
    Depends on vulnerable versions of @microsoft/recognizers-text-date-time
    Depends on vulnerable versions of @microsoft/recognizers-text-number
    Depends on vulnerable versions of @microsoft/recognizers-text-number-with-unit
    node_modules/@microsoft/recognizers-text-suite
      @nlpjs/builtin-microsoft  *
      Depends on vulnerable versions of @microsoft/recognizers-text-suite
      node_modules/@nlpjs/builtin-microsoft

**Comment by Chard0212** [comment]
ℹ️  Installing spaCy models...
🚨 Failed to install the Python packages: Error: Command failed with exit code 1: pipenv run spacy download en_core_web_trf-3.4.0 --direct
Traceback (most recent call last):
  File "/home/chard/leon/bridges/python/.venv/bin/spacy", line 5, in <module>
    from spacy.cli import setup_cli
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/schemas.py", line 222, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 634, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "/root/.pyenv/versions/3.9.10/lib/python3.9/typing.py", line 851, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
🚨 Error: Command failed with exit code 1: pipenv run spacy download en_core_web_trf-3.4.0 --direct
Traceback (most recent call last):
  File "/home/chard/leon/bridges/python/.venv/bin/spacy", line 5, in <module>
    from spacy.cli import setup_cli
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/pipeline/__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy/vocab.pyx", line 1, in init spacy.vocab
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/tokens/__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc
  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/schemas.py", line 222, in <module>
    class TokenPattern(BaseModel):
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 634, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 641, in pydantic.fields.ModelField._type_analysis
  File "/root/.pyenv/versions/3.9.10/lib/python3.9/typing.py", line 851, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
    at makeError (/home/chard/leon/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/chard/leon/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at installPythonPackages (/home/chard/leon/scripts/setup/setup-python-packages.js:47:9)
    at /home/chard/leon/scripts/setup/setup-python-packages.js:64:13 {
  shortMessage: 'Command failed with exit code 1: pipenv run spacy download en_core_web_trf-3.4.0 --direct',
  command: 'pipenv run spacy download en_core_web_trf-3.4.0 --direct',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Traceback (most recent call last):\n' +
    '  File "/home/chard/leon/bridges/python/.venv/bin/spacy", line 5, in <module>\n' +
    '    from spacy.cli import setup_cli\n' +
    '  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/__init__.py", line 14, in <module>\n' +
    '    from . import pipeline  # noqa: F401\n' +
    '  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/pipeline/__init__.py", line 1, in <module>\n' +
    '    from .attributeruler import AttributeRuler\n' +
    '  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/pipeline/attributeruler.py", line 6, in <module>\n' +
    '    from .pipe import Pipe\n' +
    '  File "spacy/pipeline/pipe.pyx", line 1, in init spacy.pipeline.pipe\n' +
    '  File "spacy/vocab.pyx", line 1, in init spacy.vocab\n' +
    '  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/tokens/__init__.py", line 1, in <module>\n' +
    '    from .doc import Doc\n' +
    '  File "spacy/tokens/doc.pyx", line 36, in init spacy.tokens.doc\n' +
    '  File "/home/chard/leon/bridges/python/.venv/lib/python3.9/site-packages/spacy/schemas.py", line 222, in <module>\n' +
    '    class TokenPattern(BaseModel):\n' +
    '  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__\n' +
    '  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer\n' +
    '  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__\n' +
    '  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare\n' +
    '  File "pydantic/fields.py", line 634, in pydantic.fields.ModelField._type_analysis\n' +
    '  File "pydantic/fields.py", line 641, in pydantic.fields.ModelField._type_analysis\n' +
    '  File "/root/.pyenv/versions/3.9.10/lib/python3.9/typing.py", line 851, in __subclasscheck__\n' +
    '    return issubclass(cls, self.__origin__)\n' +
    'TypeError: issubclass() arg 1 must be a class',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

**Comment by Chard0212** [comment]
> Look at your report: https://report.getleon.ai/raw/exomuvuseg
> 
> It seems that you have less than 2 GB of total RAM. Leon needs at least ~ 4 GB. Also, I'm not sure about your disk space, but it may also be possible that the TCP server cannot be extracted properly because you don't have enough space there too.

enough memory and storage, just TCP server wont success installing and when check for errors wont show.. is there a way I could download and install the tcp server manually

**Comment by ZephyrAmmor** [comment]
##  Cannot start the TCP server: /bin/sh: line 1: tcp_server/dist/linux-x86_64/leon-tcp-server: No such file or directory

    ~  leon check                                         INT ✘  system  

> leon@1.0.0-beta.8 check
> ts-node scripts/check.js



.: CHECKING :.
ℹ️  Leon version
✅ 1.0.0-beta.8

ℹ️  Environment
✅ Total RAM: 15.5 GB
(node:11395) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
✅ {"type":"Linux","platform":"linux","arch":"x64","cpus":4,"release":"6.12.38-1-MANJARO","osName":"Linux 6.12","distro":{"os":"linux","dist":"Manjaro Linux","codename":"\"zetar\"","release":"\"25.0.6\""}}

ℹ️  node --version
✅ v24.4.0

ℹ️  npm --version
✅ 11.4.2

✅ Python bridge version: 1.0.1
ℹ️  Executing a skill...
ℹ️  bridges/python/dist/linux-x86_64/leon-python-bridge "/home/zephyr/.leon/scripts/assets/intent-object.json"
✅ {"domain": "leon", "skill": "random_number", "action": "run", "lang": "en", "utterance": "Give me a random number", "entities": [], "slots": {}, "output": {"type": "end", "codes": ["38"], "speech": "38", "core": {}, "options": {}}}
ℹ️  Skill execution time: 346ms

✅ TCP server version: 1.0.0
ℹ️  Starting the TCP server...
ℹ️  tcp_server/dist/linux-x86_64/leon-tcp-server en
🚨 Cannot start the TCP server: /bin/sh: line 1: tcp_server/dist/linux-x86_64/leon-tcp-server: No such file or directory

ℹ️  TCP server startup time: 72ms

ℹ️  Global resolvers NLP model state
✅ Found and valid

ℹ️  Skills resolvers NLP model state
✅ Found and valid

ℹ️  Main NLP model state
✅ Found and valid

ℹ️  Amazon Polly TTS
⚠️  Amazon Polly TTS is not yet configured

ℹ️  Google Cloud TTS/STT
⚠️  Google Cloud TTS/STT is not yet configured

ℹ️  Watson TTS
⚠️  Watson TTS is not yet configured

ℹ️  Offline TTS
⚠️  Cannot find bin/flite/flite. You can set up the offline TTS by running: "npm run setup:offline-tts"

ℹ️  Watson STT
⚠️  Watson STT is not yet configured

ℹ️  Offline STT
⚠️  Cannot find bin/coqui/huge-vocabulary.scorer. You can setup the offline STT by running: "npm run setup:offline-stt"


.: REPORT :.
ℹ️  Here is the diagnosis about your current setup
✅ Run
✅ Run skills
✅ Reply you by texting
🚨 Start the TCP server
⚠️  Amazon Polly text-to-speech
⚠️  Google Cloud text-to-speech
⚠️  Watson text-to-speech
⚠️  Offline text-to-speech
⚠️  Google Cloud speech-to-text
⚠️  Watson speech-to-text
⚠️  Offline speech-to-text

🚨 Please fix the errors above


.: REPORT URL :.
ℹ️  Sending report...
✅ Report URL: https://report.getleon.ai/raw/upegobovek

**Comment by zh-impact** [comment]
If you are running on Windows, maybe you need to change the port.
e.g.
```shell
leon start --port 31337
```
and change the `LEON_PY_TCP_SERVER_PORT` in `$User\.leon\.env` file.
