### ISSUE TITLE
npm start error while checking skills data

### ISSUE THREAD

**Issue by TheAnalist** [leon-ai/leon#492]
### Specs

- Leon version: 1.0.0-beta.9
- OS (or browser) version: gitpod link avaliable in documentation
- Node.js version: 18.16.0

### Expected Behavior
normal leon start

### Actual Behavior
Error:

✅ Global data schemas checked
ℹ️  Checking skills data schemas...
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module 'skills/business_finance/domain.json'
Require stack:
- /workspace/leon/server/dist/helpers/skill-domain-helper.js
- /workspace/leon/server/dist/pre-check.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /workspace/leon/server/dist/helpers/skill-domain-helper.js:43:150
    at async /workspace/leon/server/dist/helpers/skill-domain-helper.js:43:47
    at async Promise.all (index 0)
    at async SkillDomainHelper.getSkillDomains (/workspace/leon/server/dist/helpers/skill-domain-helper.js:39:9)
    at async /workspace/leon/server/dist/pre-check.js:119:26 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/leon/server/dist/helpers/skill-domain-helper.js',
    '/workspace/leon/server/dist/pre-check.js'
  ]
}

**Comment by louistiti** [comment]
Hi, thanks for the report, I just published a fix a few minutes ago.
