### ISSUE TITLE
cannot start the TCP server - GLIBC_2.35 not found

### ISSUE THREAD

**Issue by negue** [leon-ai/leon#500]
### Specs

- Leon version: 1.0.0-beta.9+dev
- OS (or browser) version: MacOS M1 Pro - Ventura 13.4.1 
- Node.js version: v16.18.0
- Complete "leon check" (or "npm run check") output:

.: CHECKING :.
ℹ️  Leon version
✅ 1.0.0-beta.9+dev

ℹ️  Environment
✅ Free RAM: 4.47 GB | Total RAM: 5.13 GB
✅ {"type":"Linux","platform":"linux","arch":"arm64","cpus":8,"release":"6.3.12-orbstack-00210-ga4f4fae8883e","osName":"Linux 6.3","distro":{"os":"linux","dist":"Ubuntu","codename":"focal","release":"20.04"}}

ℹ️  node --version
✅ v16.18.0

ℹ️  npm --version
✅ 8.19.2

✅ Node.js bridge version: 1.0.0
ℹ️  Executing a skill...
ℹ️  /home/docker/leon/node_modules/ts-node/dist/bin.js --swc /home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js "/home/docker/leon/scripts/assets/nodejs-bridge-intent-object.json"
✅ Python bridge version: 1.1.0
🚨 Error: Command failed with exit code 1: /home/docker/leon/node_modules/ts-node/dist/bin.js --swc /home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js "/home/docker/leon/scripts/assets/nodejs-bridge-intent-object.json"
/home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js:146
exports.SKILL_CONFIG = JSON.parse(node_fs_1.default.readFileSync(node_path_1.default.join(exports.SKILL_PATH, 'config', exports.INTENT_OBJECT.extra_context_data.lang + '.json'), 'utf8'));
                                                                                                                                                                 ^
TypeError: Cannot read properties of undefined (reading 'lang')
    at Object.call (/home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js:146:162)
    at __nccwpck_require__ (/home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js:558:43)
    at Object.call (/home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js:187:21)
    at __nccwpck_require__ (/home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js:558:43)
    at /home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js:578:37
    at Object.<anonymous> (/home/docker/leon/bridges/nodejs/dist/bin/leon-nodejs-bridge.js:581:10)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module.m._compile (/home/docker/leon/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .js] (/home/docker/leon/node_modules/ts-node/src/index.ts:1621:12)

ℹ️  Executing a skill...
ℹ️  /home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge "/home/docker/leon/scripts/assets/python-bridge-intent-object.json"
🚨 Error: Command failed with exit code 1: /home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge "/home/docker/leon/scripts/assets/python-bridge-intent-object.json"
/home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge)
/home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge)
/home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge)
/home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/docker/leon/bridges/python/dist/linux-aarch64/leon-python-bridge)

✅ TCP server version: 1.0.0
ℹ️  Starting the TCP server...
ℹ️  /home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server en
ℹ️  TCP server startup time: 5ms

ℹ️  Global resolvers NLP model state
🚨 Cannot start the TCP server: /home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server)
/home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server)
/home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server)
/home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/docker/leon/tcp_server/dist/linux-aarch64/leon-tcp-server)

✅ Found and valid

ℹ️  Skills resolvers NLP model state
✅ Found and valid

ℹ️  Main NLP model state
✅ Found and valid

ℹ️  Amazon Polly TTS
ℹ️  Google Cloud TTS/STT
⚠️  Amazon Polly TTS is not yet configured

ℹ️  Watson TTS
⚠️  Google Cloud TTS/STT is not yet configured

⚠️  Watson TTS is not yet configured

ℹ️  Offline TTS
ℹ️  Watson STT
⚠️  Cannot find bin/flite/flite. You can set up the offline TTS by running: "npm run setup:offline-tts"

⚠️  Watson STT is not yet configured

ℹ️  Offline STT
⚠️  Cannot find bin/coqui/huge-vocabulary.scorer. You can setup the offline STT by running: "npm run setup:offline-stt"

.: REPORT :.
ℹ️  Here is the diagnosis about your current setup
✅ Run
✅ Reply you by texting
🚨 Run skills
🚨 Start the TCP server
⚠️  Amazon Polly text-to-speech
⚠️  Google Cloud text-to-speech
⚠️  Watson text-to-speech
⚠️  Offline text-to-speech
⚠️  Google Cloud speech-to-text
⚠️  Watson speech-to-text
⚠️  Offline speech-to-text

🚨 Please fix the errors above

.: REPORT URL :.
ℹ️  Sending report...
✅ Report URL: https://report.getleon.ai/raw/gohehudico

### Extra (like a sample repo to reproduce the issue, etc.)

This is after adding python3 to the Dockerfile #499  , so maybe some more packages are missing with the GLIBC?

**Comment by OpenElectronika** [comment]
Same issue
