### ISSUE TITLE
Cannot start the TCP server - 

### ISSUE THREAD

**Issue by sk2eu** [leon-ai/leon#523]
Anyone have an idea why it won't start?

### Specs

ℹ️  Leon version
✅ 1.0.0-beta.8

ℹ️  Environment
✅ Total RAM: 31.93 GB
✅ {"type":"Windows_NT","platform":"win32","arch":"x64","cpus":12,"release":"10.0.19045","osName":"Windows 10","distro":null}

ℹ️  node --version
✅ v22.0.0

ℹ️  npm --version
✅ 10.5.1

✅ Python bridge version: 1.0.1
ℹ️  Executing a skill...
ℹ️  bridges\python\dist\win-amd64\leon-python-bridge "C:\Users\bbb\.leon\scripts\assets\intent-object.json"
✅ {"domain": "leon", "skill": "random_number", "action": "run", "lang": "en", "utterance": "Give me a random number", "entities": [], "slots": {}, "output": {"type": "end", "codes": ["3"], "speech": "3", "core": {}, "options": {}}}
ℹ️  Skill execution time: 333ms

✅ TCP server version: 1.0.0
ℹ️  Starting the TCP server...
ℹ️  tcp_server\dist\win-amd64\leon-tcp-server en
🚨 Cannot start the TCP server: Traceback (most recent call last):
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>

###################################################################
`Microsoft Windows [Version 10.0.19045.4355]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>python -m pip install numpy --upgrade
Requirement already satisfied: numpy in c:\program files\python312\lib\site-packages (1.26.4)

C:\Windows\system32>leon check

> leon@1.0.0-beta.8 check
> ts-node scripts/check.js

.: CHECKING :.
ℹ️  Leon version
✅ 1.0.0-beta.8

ℹ️  Environment
✅ Total RAM: 31.93 GB
✅ {"type":"Windows_NT","platform":"win32","arch":"x64","cpus":12,"release":"10.0.19045","osName":"Windows 10","distro":null}

ℹ️  node --version
✅ v22.0.0

ℹ️  npm --version
✅ 10.5.1

✅ Python bridge version: 1.0.1
ℹ️  Executing a skill...
ℹ️  bridges\python\dist\win-amd64\leon-python-bridge "C:\Users\bbb\.leon\scripts\assets\intent-object.json"
✅ {"domain": "leon", "skill": "random_number", "action": "run", "lang": "en", "utterance": "Give me a random number", "entities": [], "slots": {}, "output": {"type": "end", "codes": ["3"], "speech": "3", "core": {}, "options": {}}}
ℹ️  Skill execution time: 333ms

✅ TCP server version: 1.0.0
ℹ️  Starting the TCP server...
ℹ️  tcp_server\dist\win-amd64\leon-tcp-server en
🚨 Cannot start the TCP server: Traceback (most recent call last):
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>

ℹ️  TCP server startup time: 133ms

ℹ️  Global resolvers NLP model state
🚨 Cannot start the TCP server:   File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\overrides.py", line 8, in <module>
ImportError: DLL load failed while importing _multiarray_umath: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\__init__.py", line 158, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\__config__.py", line 4, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\bbb\.leon\tcp_server\dist\win-amd64\leon-tcp-server.exe"
  * The NumPy version is: "1.26.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: Das angegebene Modul wurde nicht gefunden.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\leon\leon\tcp_server\src\.venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 120, in run
  File "D:\a\leon\leon\tcp_server\src\.venv\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 16, in run
  File "tcp_server\src\main.py", line 5, in <module>
    from os.path import join, dirname
  File "D:\a\leon\leon\tcp_server\src\lib\nlp.py", line 3, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\spacy\__init__.py", line 6, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\spacy\errors.py", line 2, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\spacy\compat.py", line 3, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\thinc\__init__.py", line 2, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\__init__.py", line 163, in <module>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

✅ Found and valid

ℹ️  Skills resolvers NLP model state
✅ Found and valid

ℹ️  Main NLP model state
✅ Found and valid

ℹ️  Amazon Polly TTS
⚠️  Amazon Polly TTS is not yet configured

ℹ️  Google Cloud TTS/STT
⚠️  Google Cloud TTS/STT is not yet configured

ℹ️  Watson TTS
⚠️  Watson TTS is not yet configured

ℹ️  Offline TTS
⚠️  Cannot find bin/flite/flite. You can set up the offline TTS by running: "npm run setup:offline-tts"

ℹ️  Watson STT
⚠️  Watson STT is not yet configured

ℹ️  Offline STT
⚠️  Cannot find bin/coqui/huge-vocabulary.scorer. You can setup the offline STT by running: "npm run setup:offline-stt"

.: REPORT :.
ℹ️  Here is the diagnosis about your current setup
✅ Run
✅ Run skills
✅ Reply you by texting
🚨 Start the TCP server
⚠️  Amazon Polly text-to-speech
⚠️  Google Cloud text-to-speech
⚠️  Watson text-to-speech
⚠️  Offline text-to-speech
⚠️  Google Cloud speech-to-text
⚠️  Watson speech-to-text
⚠️  Offline speech-to-text

🚨 Please fix the errors above

.: REPORT URL :.
ℹ️  Sending report...
✅ Report URL: https://report.getleon.ai/raw/avovemovet`

c:\>python -m pip install -U --no-cache-dir --no-deps --force-reinstall --upgrade-strategy only-if-needed certifi distlib filelock pipenv platformdirs virtualenv
Collecting certifi
  Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting distlib
  Downloading distlib-0.3.8-py2.py3-none-any.whl.metadata (5.1 kB)
Collecting filelock
  Downloading filelock-3.13.4-py3-none-any.whl.metadata (2.8 kB)
Collecting pipenv
  Downloading pipenv-2023.12.1-py3-none-any.whl.metadata (19 kB)
Collecting platformdirs
  Downloading platformdirs-4.2.1-py3-none-any.whl.metadata (11 kB)
Collecting virtualenv
  Downloading virtualenv-20.26.0-py3-none-any.whl.metadata (4.4 kB)
Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
   ---------------------------------------- 163.8/163.8 kB 3.3 MB/s eta 0:00:00
Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
   ---------------------------------------- 468.9/468.9 kB 7.3 MB/s eta 0:00:00
Downloading filelock-3.13.4-py3-none-any.whl (11 kB)
Downloading pipenv-2023.12.1-py3-none-any.whl (3.1 MB)
   ---------------------------------------- 3.1/3.1 MB 6.2 MB/s eta 0:00:00
Downloading platformdirs-4.2.1-py3-none-any.whl (17 kB)
Downloading virtualenv-20.26.0-py3-none-any.whl (3.9 MB)
   ---------------------------------------- 3.9/3.9 MB 6.1 MB/s eta 0:00:00
Installing collected packages: distlib, virtualenv, platformdirs, pipenv, filelock, certifi
  Attempting uninstall: distlib
    Found existing installation: distlib 0.3.8
    Uninstalling distlib-0.3.8:
      Successfully uninstalled distlib-0.3.8
  Attempting uninstall: virtualenv
    Found existing installation: virtualenv 20.26.0
    Uninstalling virtualenv-20.26.0:
      Successfully uninstalled virtualenv-20.26.0
  Attempting uninstall: platformdirs
    Found existing installation: platformdirs 4.2.1
    Uninstalling platformdirs-4.2.1:
      Successfully uninstalled platformdirs-4.2.1
  Attempting uninstall: pipenv
    Found existing installation: pipenv 2023.12.1
    Uninstalling pipenv-2023.12.1:
      Successfully uninstalled pipenv-2023.12.1
  Attempting uninstall: filelock
    Found existing installation: filelock 3.13.4
    Uninstalling filelock-3.13.4:
      Successfully uninstalled filelock-3.13.4
  Attempting uninstall: certifi
    Found existing installation: certifi 2024.2.2
    Uninstalling certifi-2024.2.2:
      Successfully uninstalled certifi-2024.2.2
Successfully installed certifi-2024.2.2 distlib-0.3.8 filelock-3.13.4 pipenv-2023.12.1 platformdirs-4.2.1 virtualenv-20.26.0

c:\>python --version
Python 3.12.3

c:\>cd C:\Users\bbb\.leon\tcp_server\dist\win-amd64

C:\Users\bbb\.leon\tcp_server\dist\win-amd64>leon-tcp-server.exe
Traceback (most recent call last):
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\multiarray.py", line 10, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\overrides.py", line 8, in <module>
ImportError: DLL load failed while importing _multiarray_umath: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\__init__.py", line 158, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\__config__.py", line 4, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "C:\Users\bbb\.leon\tcp_server\dist\win-amd64\leon-tcp-server.exe"
  * The NumPy version is: "1.26.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: Das angegebene Modul wurde nicht gefunden.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\leon\leon\tcp_server\src\.venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 120, in run
  File "D:\a\leon\leon\tcp_server\src\.venv\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 16, in run
  File "tcp_server\src\main.py", line 5, in <module>
  File "D:\a\leon\leon\tcp_server\src\lib\nlp.py", line 3, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\spacy\__init__.py", line 6, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\spacy\errors.py", line 2, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\spacy\compat.py", line 3, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\thinc\__init__.py", line 2, in <module>
  File "D:\a\leon\leon\tcp_server\src\.venv\lib\site-packages\numpy\__init__.py", line 163, in <module>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

C:\Users\bbb\.leon\tcp_server\dist\win-amd64>

![grafik](https://github.com/leon-ai/leon/assets/48036204/c43a93f1-1ca0-46da-99fb-226dc883382f)

![grafik](https://github.com/leon-ai/leon/assets/48036204/59b6a00a-7fcc-46f5-a4ef-68c8574a5623)

**Comment by samow10** [comment]
same issue anyone to help
