### ISSUE TITLE
Spotify Package

### ISSUE THREAD

**Issue by Zeikko** [leon-ai/leon#64]
### Feature Use Case

- Play a song
- Play an album
- Play songs of an artist
- Stop music
- Resume music
- Set volume
- Tell what are we listening to

```
# Example
--> Leon, play The Fat Rat
<-- Ok, playing the calling by TheFatRat
```

### Feature Proposal

Implement a feature to use the Spotify web API to find the music that the use is looking for and play with a device that is available through the API.

**Comment by jtorresdev** [comment]
Hi @Zeikko , I have some worked on this package https://github.com/jtorresdev/leonify

**Comment by Zeikko** [comment]
Cool! Great work! I just tried it out and got this error: `✖ The "Leonify" package configuration file does not exist. Try to pull the project (git pull)` when running `npm install` in leon root.
Also the leonify dependencies are missing so I get this when trying to play a song:
```
✖ Traceback (most recent call last):
  File "bridges/python/main.py", line 23, in <module>
    main()
  File "bridges/python/main.py", line 18, in main
    m = import_module('packages.' + package + '.' + module)
  File "/home/zeikko/Documents/Projects/leon/bridges/python/.venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./packages/leonify/play.py", line 3, in <module>
    from .leonify import getDeviceId, sp_request, getCurrentSong
  File "./packages/leonify/leonify.py", line 10, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by jtorresdev** [comment]
try installing six module `pip install six`

**Comment by louistiti** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [✨ Music Package](https://trello.com/c/kX7Mv9Iv/58-%E2%9C%A8-music-package)

**Comment by louistiti** [comment]
Hello @Zeikko,

Thanks for suggesting! A while ago I planned to create a Music package containing a Spotify module as you can see on the [roadmap](https://trello.com/c/kX7Mv9Iv/58-%E2%9C%A8-music-package). But depending how Leon will evolve until there, maybe a Spotify package will be more appropriate, let's see.

@jtorresdev it looks awesome! 👏

**Comment by nrj5k** [comment]
Why not an mpd client on Leon and users can configure their own sources from there as well?

**Comment by louistiti** [comment]
Hello @nrj5k,

It is an interesting idea. But for now I prefer to minimize the type of clients. However, that's something we could implement directly on the top of the existing client.

**Comment by nrj5k** [comment]
I like the sound of that.

**Comment by louistiti** [comment]
Today the web app client is a simple messaging interface, but later we could imagine that will be a bit more complex than that with cool features 😃

**Comment by rachel-l-sanchez** [comment]
Could I contribute to this issue?

**Comment by louistiti** [comment]
> Could I contribute to this issue? 

Sure! But I suggest to wait a bit until the official release as the whole core of Leon is being rewritten and several breaking changes will take place.
In the meantime, you can [join us on Discord](https://discord.gg/MNQqqKg). Once the stable version shipped, we'll all be working together on creating new skills for Leon.
