### ISSUE TITLE
Watson STT & TSS Failures

### ISSUE THREAD

**Issue by mbwhite** [leon-ai/leon#83]
### Specs

- Leon version: master branch
- OS (or browser) version: Ubuntu 18
- Node.js version: 10 
- Complete "npm run check" output:
- (optional) Leon package version:

### Actual Behavior
✖ Watson STT: Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password, api_key, and iam_access_token.

and 
/home/matthew/leon/server/dist/tts/watson-tts/synthesizer.js:78
  client.synthesize(synthesizer.conf, (err, audio) => {
         ^

TypeError: client.synthesize is not a function
    at Object.synthesizer.save (/home/matthew/leon/server/dist/tts/watson-tts/synthesizer.js:78:10)
    at Tts.forward (/home/matthew/leon/server/dist/tts/tts.js:73:30)
    at Tts.add (/home/matthew/leon/server/dist/tts/tts.js:121:12)
    at Brain.talk (/home/matthew/leon/server/dist/core/brain.js:67:18)
    at Socket.process.stdout.on (/home/matthew/leon/server/dist/core/brain.js:169:16)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

### How Do We Reproduce?
Configure Watson Services and start Leon
### Extra (like a sample repo to reproduce the issue, etc.)

I will start investigating; but probably check the dev branch first incase the issues are fixed there.

**Comment by mbwhite** [comment]
Can confirm this is resolved on the dev branch.
